// ReSharper disable CppClangTidyModernizeMacroToEnum
#pragma once

#include <Engine/Core/Definitions.h>

#define SNOWBITE_VERSION_MAJOR 0
#define SNOWBITE_VERSION_MINOR 0
#define SNOWBITE_VERSION_PATCH 0
#define SNOWBITE_VERSION_BRANCH "dev"

#define SNOWBITE_VERSION SB_MAKE_VERSION(SNOWBITE_VERSION_MAJOR, SNOWBITE_VERSION_MINOR, SNOWBITE_VERSION_PATCH)
